// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaAFx6eX8-Xh68MhRBVHjkS1zIdPANS0k',
    appId: '1:58365192123:web:3a1309de9424a5cfd8869e',
    messagingSenderId: '58365192123',
    projectId: 'lol-check',
    authDomain: 'lol-check.firebaseapp.com',
    storageBucket: 'lol-check.firebasestorage.app',
    measurementId: 'G-35LT9F6XXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk7xt-IyfRvI4UH4MRFWb5fq_J8HeV4HQ',
    appId: '1:58365192123:android:85cc0dbebe405578d8869e',
    messagingSenderId: '58365192123',
    projectId: 'lol-check',
    storageBucket: 'lol-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcPZSC0QV8mJpgII1z6sah_-hOhr5NeLQ',
    appId: '1:58365192123:ios:4aaf765755e98477d8869e',
    messagingSenderId: '58365192123',
    projectId: 'lol-check',
    storageBucket: 'lol-check.firebasestorage.app',
    iosBundleId: 'com.example.lolcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcPZSC0QV8mJpgII1z6sah_-hOhr5NeLQ',
    appId: '1:58365192123:ios:4aaf765755e98477d8869e',
    messagingSenderId: '58365192123',
    projectId: 'lol-check',
    storageBucket: 'lol-check.firebasestorage.app',
    iosBundleId: 'com.example.lolcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaAFx6eX8-Xh68MhRBVHjkS1zIdPANS0k',
    appId: '1:58365192123:web:125dde2da211068ad8869e',
    messagingSenderId: '58365192123',
    projectId: 'lol-check',
    authDomain: 'lol-check.firebaseapp.com',
    storageBucket: 'lol-check.firebasestorage.app',
    measurementId: 'G-714687FN78',
  );

}